# Generated by Django 3.2 on 2021-09-02 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SteamID',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('steamid', models.CharField(max_length=17, verbose_name='SteamID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'SteamID',
                'verbose_name_plural': 'SteamID`s',
                'ordering': ('pub_date',),
            },
        ),
    ]
