# Generated by Django 3.2 on 2021-09-04 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('getvac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteamInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('steamid', models.CharField(max_length=200, verbose_name='steamid')),
                ('communityvisibilitystate', models.CharField(max_length=200, verbose_name='communityvisibilitystate')),
                ('profilestate', models.CharField(max_length=200, verbose_name='profilestate')),
                ('personaname', models.CharField(max_length=200, verbose_name='personaname')),
                ('commentpermission', models.CharField(max_length=200, verbose_name='commentpermission')),
                ('profileurl', models.CharField(max_length=200, verbose_name='profileurl')),
                ('avatar', models.CharField(max_length=200, verbose_name='avatar')),
                ('avatarmedium', models.CharField(max_length=200, verbose_name='avatarmedium')),
                ('avatarfull', models.CharField(max_length=200, verbose_name='avatarfull')),
                ('avatarhash', models.CharField(max_length=200, verbose_name='avatarhash')),
                ('lastlogoff', models.CharField(max_length=200, verbose_name='lastlogoff')),
                ('personastate', models.CharField(max_length=200, verbose_name='personastate')),
                ('realname', models.CharField(max_length=200, verbose_name='realname')),
                ('primaryclanid', models.CharField(max_length=200, verbose_name='primaryclanid')),
                ('timecreated', models.CharField(max_length=200, verbose_name='timecreated')),
                ('personastateflags', models.CharField(max_length=200, verbose_name='personastateflags')),
                ('loccountrycode', models.CharField(max_length=200, verbose_name='loccountrycode')),
                ('locstatecode', models.CharField(max_length=200, verbose_name='locstatecode')),
                ('loccityid', models.CharField(max_length=200, verbose_name='loccityid')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'SteamInfo',
                'verbose_name_plural': 'SteamInfo`s',
                'ordering': ('pub_date',),
            },
        ),
    ]
