# Generated by Django 3.2 on 2021-09-04 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('getvac', '0002_steaminfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('steamid', models.CharField(max_length=200, verbose_name='steamid')),
                ('CommunityBanned', models.CharField(max_length=200, verbose_name='CommunityBanned')),
                ('VACBanned', models.CharField(max_length=200, verbose_name='VACBanned')),
                ('NumberOfVACBans', models.CharField(max_length=200, verbose_name='NumberOfVACBans')),
                ('DaysSinceLastBan', models.CharField(max_length=200, verbose_name='DaysSinceLastBan')),
                ('NumberOfGameBans', models.CharField(max_length=200, verbose_name='NumberOfGameBans')),
                ('EconomyBan', models.CharField(max_length=200, verbose_name='EconomyBan')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'VacInfo',
                'verbose_name_plural': 'SteamInfo`s',
                'ordering': ('pub_date',),
            },
        ),
    ]
